# Data paths
data:
  train_path: "inputData/train/train_data.csv"
  test_path: "inputData/test/test_data.csv"
  inference_path: "inputData/inference/inference_data.csv"
  model_save_path: "modelData/trained_model.pth"

# Model parameters
model:
  input_size: 10  # Number of features
  hidden_size: 64
  num_layers: 2
  dropout: 0.1
  learning_rate: 0.001
  weight_decay: 1e-5

# Training parameters
training:
  batch_size: 32
  num_epochs: 100
  early_stopping_patience: 10
  validation_split: 0.2
  target_column: "target"  # Name of the target column in your CSV
  feature_columns:  # List of feature columns to use
    - "feature1"
    - "feature2"
    - "feature3"
    # Add more features as needed

# Inference parameters
inference:
  batch_size: 32
  output_path: "inputData/inference/predictions.csv" 