# Data paths
data:
  train_path: "data/train.csv"
  test_path: "data/test.csv"
  inference_path: "inputData/inference/inference_data.csv"
  timestamp: "20240320"
  model_save_path: "models/saved_models/model_{{timestamp}}.pth"

# Model parameters
model:
  # Input/Output dimensions
  enc_in: 7  # Number of input features
  dec_in: 1  # Number of target features
  c_out: 1   # Number of output features
  seq_len: 96    # Input sequence length (1 day with 15-min intervals)
  label_len: 48  # Start token length
  out_len: 24    # Prediction sequence length (6 hours)
  
  # Model architecture
  factor: 5
  d_model: 512
  n_heads: 8
  e_layers: 2
  d_layers: 1
  d_ff: 2048
  dropout: 0.05
  attn: "prob"
  embed: "timeF"
  freq: "h"
  activation: "gelu"
  output_attention: false
  distil: true
  mix: true

# Training parameters
training:
  batch_size: 32
  num_epochs: 100
  validation_split: 0.1
  early_stopping_patience: 10
  learning_rate: 0.001
  time_column: "datetime"
  feature_columns:
    - "Global_active_power"
    - "Global_reactive_power"
    - "Voltage"
    - "Global_intensity"
    - "Sub_metering_1"
    - "Sub_metering_2"
    - "Sub_metering_3"
  target_column: "Global_active_power"

# Inference parameters
inference:
  batch_size: 32
  output_path: "data/predictions_{{timestamp}}.csv" 